// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WanderMeet.Api.Infrastructure.EntityFramework;

#nullable disable

namespace WanderMeet.Api.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(WanderMeetDbContext))]
    [Migration("20260509152552_AddFcmTokenToUser")]
    partial class AddFcmTokenToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_cities_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Name", "Country")
                        .HasDatabaseName("ix_cities_name_country");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.HangoutTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("emoji");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("label");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hangout_tags");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_hangout_tags_slug");

                    b.ToTable("hangout_tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Emoji = "☕",
                            Label = "Coffee",
                            Slug = "Coffee"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Emoji = "🚶",
                            Label = "Walk",
                            Slug = "Walk"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Emoji = "🍽️",
                            Label = "Food",
                            Slug = "Food"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Emoji = "🗺️",
                            Label = "Explore",
                            Slug = "Explore"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Emoji = "💻",
                            Label = "Cowork",
                            Slug = "Cowork"
                        });
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("HangoutTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("hangout_tag_id");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<bool>("SenderIsThere")
                        .HasColumnType("boolean")
                        .HasColumnName("sender_is_there");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_invites");

                    b.HasIndex("HangoutTagId")
                        .HasDatabaseName("ix_invites_hangout_tag_id");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_invites_place_id");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_invites_receiver_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_invites_sender_id");

                    b.HasIndex("ReceiverId", "Status")
                        .HasDatabaseName("ix_invites_receiver_id_status");

                    b.HasIndex("SenderId", "Status")
                        .HasDatabaseName("ix_invites_sender_id_status");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_invites_status_expires_at");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.Meetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("InviteId")
                        .HasColumnType("uuid")
                        .HasColumnName("invite_id");

                    b.Property<DateTimeOffset>("MetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("met_at");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<bool>("PromptSent")
                        .HasColumnType("boolean")
                        .HasColumnName("prompt_sent");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_a_id");

                    b.Property<Guid>("UserBId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_b_id");

                    b.HasKey("Id")
                        .HasName("pk_meetups");

                    b.HasIndex("InviteId")
                        .IsUnique()
                        .HasDatabaseName("ix_meetups_invite_id");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_meetups_place_id");

                    b.HasIndex("UserAId")
                        .HasDatabaseName("ix_meetups_user_a_id");

                    b.HasIndex("UserBId")
                        .HasDatabaseName("ix_meetups_user_b_id");

                    b.HasIndex("PromptSent", "MetAt")
                        .HasDatabaseName("ix_meetups_prompt_sent_met_at");

                    b.ToTable("meetups", (string)null);
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.MeetupReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("DidMeet")
                        .HasColumnType("boolean")
                        .HasColumnName("did_meet");

                    b.Property<bool>("FeltSafe")
                        .HasColumnType("boolean")
                        .HasColumnName("felt_safe");

                    b.Property<bool>("GoodConvo")
                        .HasColumnType("boolean")
                        .HasColumnName("good_convo");

                    b.Property<Guid>("MeetupId")
                        .HasColumnType("uuid")
                        .HasColumnName("meetup_id");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewee_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("Text")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WouldMeetAgain")
                        .HasColumnType("boolean")
                        .HasColumnName("would_meet_again");

                    b.HasKey("Id")
                        .HasName("pk_meetup_reviews");

                    b.HasIndex("MeetupId")
                        .HasDatabaseName("ix_meetup_reviews_meetup_id");

                    b.HasIndex("RevieweeId")
                        .HasDatabaseName("ix_meetup_reviews_reviewee_id");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("ix_meetup_reviews_reviewer_id");

                    b.HasIndex("MeetupId", "ReviewerId")
                        .IsUnique()
                        .HasDatabaseName("ix_meetup_reviews_meetup_id_reviewer_id");

                    b.ToTable("meetup_reviews", (string)null);
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GooglePlaceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("google_place_id");

                    b.Property<decimal?>("GoogleRating")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("google_rating");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("boolean")
                        .HasColumnName("has_wifi");

                    b.Property<bool>("IsQuiet")
                        .HasColumnType("boolean")
                        .HasColumnName("is_quiet");

                    b.Property<bool>("IsSoloFriendly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_solo_friendly");

                    b.Property<bool>("IsSponsored")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sponsored");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SponsorPerk")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("sponsor_perk");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WanderMeetupCount")
                        .HasColumnType("integer")
                        .HasColumnName("wander_meetup_count");

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_places_city_id");

                    b.HasIndex("GooglePlaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_places_google_place_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_places_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("WanderMeetupCount")
                        .HasDatabaseName("ix_places_wander_meetup_count");

                    b.HasIndex("CityId", "Category")
                        .HasDatabaseName("ix_places_city_id_category");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReportedId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_id");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("ReportedId")
                        .HasDatabaseName("ix_reports_reported_id");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_reports_reporter_id");

                    b.HasIndex("ReviewedAt", "CreatedAt")
                        .HasDatabaseName("ix_reports_reviewed_at_created_at");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AzureAdB2CId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("azure_ad_b2c_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("bio");

                    b.Property<int>("CitiesCount")
                        .HasColumnType("integer")
                        .HasColumnName("cities_count");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("fcm_token");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsIdVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_id_verified");

                    b.Property<bool>("IsOpenToRomance")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open_to_romance");

                    b.Property<bool>("IsOpenToday")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open_today");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("location");

                    b.Property<int>("MeetupCount")
                        .HasColumnType("integer")
                        .HasColumnName("meetup_count");

                    b.Property<int>("TrustScore")
                        .HasColumnType("integer")
                        .HasColumnName("trust_score");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("YearsNomading")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("years_nomading");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AzureAdB2CId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_azure_ad_b2c_id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_users_city_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_users_deleted_at");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_users_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("TrustScore")
                        .HasDatabaseName("ix_users_trust_score");

                    b.HasIndex("CityId", "IsOpenToday", "LastActiveAt")
                        .HasDatabaseName("ix_users_city_id_is_open_today_last_active_at");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.UserCity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ArrivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrived_at");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("DepartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departed_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_cities");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_user_cities_city_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_cities_user_id");

                    b.HasIndex("UserId", "DepartedAt")
                        .HasDatabaseName("ix_user_cities_user_id_departed_at");

                    b.ToTable("user_cities", (string)null);
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.UserHangoutTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("HangoutTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("hangout_tag_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_hangout_tags");

                    b.HasIndex("HangoutTagId")
                        .HasDatabaseName("ix_user_hangout_tags_hangout_tag_id");

                    b.HasIndex("UserId", "HangoutTagId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_hangout_tags_user_id_hangout_tag_id");

                    b.ToTable("user_hangout_tags", (string)null);
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.UserPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blob_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_photos");

                    b.HasIndex("UserId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_user_photos_user_id_order")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.ToTable("user_photos", (string)null);
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.Invite", b =>
                {
                    b.HasOne("WanderMeet.Api.Database.Entities.HangoutTag", "HangoutTag")
                        .WithMany()
                        .HasForeignKey("HangoutTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invites_hangout_tags_hangout_tag_id");

                    b.HasOne("WanderMeet.Api.Database.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invites_places_place_id");

                    b.HasOne("WanderMeet.Api.Database.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invites_users_receiver_id");

                    b.HasOne("WanderMeet.Api.Database.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invites_users_sender_id");

                    b.Navigation("HangoutTag");

                    b.Navigation("Place");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.Meetup", b =>
                {
                    b.HasOne("WanderMeet.Api.Database.Entities.Invite", "Invite")
                        .WithOne()
                        .HasForeignKey("WanderMeet.Api.Database.Entities.Meetup", "InviteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meetups_invites_invite_id");

                    b.HasOne("WanderMeet.Api.Database.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meetups_places_place_id");

                    b.HasOne("WanderMeet.Api.Database.Entities.User", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meetups_users_user_a_id");

                    b.HasOne("WanderMeet.Api.Database.Entities.User", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meetups_users_user_b_id");

                    b.Navigation("Invite");

                    b.Navigation("Place");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.MeetupReview", b =>
                {
                    b.HasOne("WanderMeet.Api.Database.Entities.Meetup", "Meetup")
                        .WithMany()
                        .HasForeignKey("MeetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meetup_reviews_meetups_meetup_id");

                    b.HasOne("WanderMeet.Api.Database.Entities.User", "Reviewee")
                        .WithMany()
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meetup_reviews_users_reviewee_id");

                    b.HasOne("WanderMeet.Api.Database.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meetup_reviews_users_reviewer_id");

                    b.Navigation("Meetup");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.Place", b =>
                {
                    b.HasOne("WanderMeet.Api.Database.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_places_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.Report", b =>
                {
                    b.HasOne("WanderMeet.Api.Database.Entities.User", "Reported")
                        .WithMany()
                        .HasForeignKey("ReportedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reports_users_reported_id");

                    b.HasOne("WanderMeet.Api.Database.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reports_users_reporter_id");

                    b.Navigation("Reported");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.User", b =>
                {
                    b.HasOne("WanderMeet.Api.Database.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.UserCity", b =>
                {
                    b.HasOne("WanderMeet.Api.Database.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_cities_cities_city_id");

                    b.HasOne("WanderMeet.Api.Database.Entities.User", "User")
                        .WithMany("Cities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_cities_users_user_id");

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.UserHangoutTag", b =>
                {
                    b.HasOne("WanderMeet.Api.Database.Entities.HangoutTag", "HangoutTag")
                        .WithMany()
                        .HasForeignKey("HangoutTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_hangout_tags_hangout_tags_hangout_tag_id");

                    b.HasOne("WanderMeet.Api.Database.Entities.User", "User")
                        .WithMany("HangoutTags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_hangout_tags_users_user_id");

                    b.Navigation("HangoutTag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.UserPhoto", b =>
                {
                    b.HasOne("WanderMeet.Api.Database.Entities.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_photos_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WanderMeet.Api.Database.Entities.User", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("HangoutTags");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
